name: Pipeline CI/CD
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest 
    steps: 
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"

      - name: Teste de Unidade
        working-directory: ./src/
        run: dotnet test ./Review-Filmes.Test.Unit/Review-Filmes.Test.Unit.csproj

      - name: Obtendo o código do projeto
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        

      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: | 
            fabricioveronez/missao-pipeline:latest
            fabricioveronez/missao-pipeline:v${{ github.run_number }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: 'image'
          image-ref: 'fabricioveronez/missao-pipeline:v${{ github.run_number }}'
          format: table
          output: 'trivy-docker-results.txt'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          hide-progress: true
                
      - name: Publicar o Trivy no Sumario
        run: |
          if [[ -s trivy-docker-results.txt ]]; then
            {
              echo "### Relatorio de Vulnerabilidades (Imagem Docker)"
              echo "<details><summary>Expandir</summary>"
              echo ""
              cat trivy-docker-results.txt
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi                  